### PR TITLE
Add documentation for filetype to set

### PR DESCRIPTION
**Pull request by axelson**

### CODE REVIEW

**Comment by wavded** [comment]
sorry I missed this, thx!

**Comment by axelson** [comment]
Thanks!

**Comment by vyp** [comment]
Wait, why? Isn't this done automatically? (It seems to be for me?) Because then isn't this confusing/redundant?

**Comment by wavded** [comment]
it appears it should be as the ftdetect directory should load on start if installed properly and contains that information:

https://github.com/wavded/vim-stylus/blob/master/ftdetect/stylus.vim

Is there a reason you needed to do this @axelson ?

**Comment by axelson** [comment]
Hmmm, that sounds like I may have a deficiency in my Vim setup.

**Pull request merged**
